name: Build Windows Client

on:
  workflow_dispatch: # اجرای دستی با دکمه

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # آپدیت شد به v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3 # آپدیت شد به v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build Binary
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4 # این همون بخشیه که ارور می‌داد، آپدیت شد به v4
        with:
          name: slipstream-exe
          path: target/release/*.exe
